defaults:
  - model@params: base
  - loss@params: base
  - override hydra/sweeper: optuna
  - _self_

hydra:
  run:
    dir: ../outputs/${settings.job_type[0]}/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s][%(name)s] - %(message)s'
  sweep:
    dir: ../multirun/${settings.job_type[0]}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    study_name: train
    direction: minimize
    n_jobs: 1
    n_trials: 10
    search_space:
      params.min_lr:
        type: float
        low: 1e-7
        high: 1e-5
        log: True

mlflow:
  enabled: False
  tracking_uri: http://127.0.0.1:5000
  experiment: sugi-cassava

wandb:
  enabled: True
  entity: imokuri
  project: cassava
  dir: ${hydra:runtime.cwd}/../cache

settings:
  print_freq: 100
  # gpus: "4,5,6,7"
  # gpus: "7"

  dirs:
    working: ${hydra:runtime.cwd}
    input: ${hydra:runtime.cwd}/../inputs/
    train_image: ${settings.dirs.input}train_images/
    test_image: ${settings.dirs.input}test_images/

  inputs:
    - train.csv
    # - test.csv
    # - sample_submission.csv

  job_type:
    # - preprocess
    - train
    # - validate
    # - inference

  dataset_type: image

  model_type: image

  # scoring: rmse
  scoring: accuracy

  debug: False
  n_debug_data: 1000

  amp: True
  multi_gpu: True

  n_class: 5

params:
  seed: 440
  n_fold: 10
  epoch: 10
  es_patience: 0
  batch_size: 32
  gradient_acc_step: 1
  max_grad_norm: 1000
