defaults:
  - override hydra/sweeper: optuna
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s][%(name)s] - %(message)s'
  sweep:
    dir: ../multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    study_name: tuning
    direction: minimize
    n_jobs: 1
    n_trials: 10
    search_space:
      params.seed:
        type: int # float
        low: 1
        high: 1000
        # step: 10
        # log: True
      params.n_fold:
        type: categorical
        choices: [5, 10]

wandb:
  enabled: False
  entity: imokuri
  project: cassava
  dir: ${hydra:runtime.cwd}/../cache

settings:
  print_freq: 100
  # gpus: "4,5,6,7"
  # gpus: "7"

  dirs:
    working: ${hydra:runtime.cwd}
    input: ${hydra:runtime.cwd}/../inputs/
    train_image: ${settings.dirs.input}train_images/
    test_image: ${settings.dirs.input}test_images/

  inputs:
    - train.csv
    # - test.csv
    # - sample_submission.csv

  dataset_type: image

  model_type: image

  # scoring: rmse
  scoring: accuracy

  debug: False
  n_debug_data: 1000

  amp: True
  multi_gpu: True

  n_class: 5

params:
  seed: 440
  n_fold: 10
  epoch: 10
  es_patience: 0
  batch_size: 32
  gradient_acc_step: 1
  max_grad_norm: 1000
  model_name: swin_base_patch4_window7_224_in22k
  size: 224
  drop_rate: 0.1
  criterion: LabelSmoothCrossEntropyLoss
  optimizer: Adam
  scheduler: CosineAnnealingWarmRestarts
  max_lr: 2e-5
  lr: 1e-5
  min_lr: 1e-6
  weight_decay: 1e-7
  label_smoothing: 1e-4
